language: Rust
cache: cargo
sudo: false
rust:
- nightly
- beta
- stable
script:
- |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo test --features nightly
    else
      cargo test
    fi