[package]
name = "languageserver-types"
version = "0.4.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Types for interaction with a language server"

repository = "https://github.com/gluon-lang/languageserver-types"
documentation = "https://docs.rs/languageserver-types"

readme = "README.md"

keywords = ["language", "server", "vscode"]

license = "MIT"

[dependencies]
enum_primitive = "0.1.0"

serde = "0.8.11"
serde_json = "0.8.0"
serde_derive = "0.8"
