[package]
name = "vscode-languageserver-types"
version = "0.1.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[dependencies]
enum_primitive = "0.1.0"

serde = "0.8.11"
serde_json = "0.8.0"
serde_derive = "0.8"
